services:
  mysql-db:
    image: mysql:8.0
    container_name: appdb-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    ports:
      - 3306:3306
    volumes:
      - app_data:/var/lib/mysql

volumes:
  app_data:
